#define LEFT_DIRECTION_PIN D12
#define LEFT_SPEED_PIN D3
#define LEFT_BRAKE_PIN D9
#define LEFT_CURRENT_PIN A0

#define RIGHT_DIRECTION_PIN D13
#define RIGHT_SPEED_PIN D11
#define RIGHT_BRAKE_PIN D8
#define RIGHT_CURRENT_PIN A1